### ISSUE TITLE
Please update to @babel7

### ISSUE THREAD

**Issue by mschipperheyn** [opencollective/opencollective-cli#15]
Hi, can you update opencollective to @babel7. I've had to remove it from a @babel7 monorepo package because it caused all sorts of havoc, even with the bridge.

**Comment by znarf** [comment]
@mschipperheyn On which repository or which package was the `opencollective` installed?

If it's for `postinstall`, we recommend to use `opencollective-postinstall` https://github.com/opencollective/opencollective-postinstall instead. This one doesn't have any dependency.

**Comment by mschipperheyn** [comment]
It was https://github.com/lingui/js-lingui
