### ISSUE TITLE
Install fails: no such file or directory .../node_modules/opencollective/dist/bin/opencollective.js

### ISSUE THREAD

**Issue by cscomfort** [opencollective/opencollective-cli#6]
Node: 8.10.0
NPM: 5.6.0
OS: RedHat 6.9 (Shared hosting)
Node Environment: NVM and Nodenv; both produce the same result

Issue: When attempting to install, the process fails when executing `npm install --save opencollective`.

```
npm ERR! path /home/userx/test/node_modules/opencollective/dist/bin/opencollective.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/userx/test/node_modules/opencollective/dist/bin/opencollective.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I should note that this does not occur on my local machine where I also use Nodenv. Any thoughts on what might be the hangup?

Thanks in advance for any help.

**Comment by xdamman** [comment]
Sorry for the issue! We just published a new lightweight postinstall without any dependency. See https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-378039208

Closing this issue for now but don't hesitate to reopen it or create a new one if you still run into some issues.
